name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: build with Maven
      run: mvn clean package

    - name: create zip package
      run: zip -j backendZupBank.zip target/*.jar
     
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-acess-key-id: "AKIAWIJIUXNFG3HFQSZZ"
        aws-secret-acess-key: ${{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}}
        aws-region: sa-east-1

    - name: Deploy to AWS Lambda
      run: aws lambda update-function-code --function-name backendZupBank --zip-file fileb://backendZupBank.zip
