name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: build with Maven
      run: mvn clean package -f ./TaahjjimBank/pom.xml
     
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Upload to S3
      run: aws s3 cp TaahjjimBank/target/TaahjjimBank-0.0.1-SNAPSHOT.jar s3://zupbankdatabase/

    - name: Deploy to AWS Lambda
      run: aws lambda update-function-code --function-name backendZupBank --s3-bucket zupbankdatabase --s3-key TaahjjimBank-0.0.1-SNAPSHOT.jar
