name: Terraform CI/CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'TaahjjimBank/**'
      - '!TaahjjimBank/infra/**'
      - '!TaahjjimBank/infra/step-functions/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - '*.tf'
      - 'TaahjjimBank/infra/step-functions/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Terraform Init
        run: terraform -chdir=TaahjjimBank/infra/step-functions init -input=false

      - name: Terraform Validate
        run: terraform -chdir=TaahjjimBank/infra/step-functions validate

      - name: Terraform Plan
        run: terraform -chdir=TaahjjimBank/infra/step-functions plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=TaahjjimBank/infra/step-functions apply -auto-approve tfplan
